// <auto-generated />
namespace Order.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20171030update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171030update));
        
        string IMigrationMetadata.Id
        {
            get { return "201710302151568_2017-10-30-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
